### ISSUE TITLE
[BUG]: build failure with old pcre2 version 10.23

### ISSUE THREAD

**Issue by remicollet** [phalcon/cphalcon#16295]
Trying to build on RHEL/CentOS 7

```
/builddir/build/BUILD/php-phalcon5-5.2.0/NTS/phalcon.zep.c:8054:2: error: unknown type name 'pcre_cache_entry'
 8054 |  pcre_cache_entry *pce;
      |  ^~~~~~~~~~~~~~~~
/builddir/build/BUILD/php-phalcon5-5.2.0/NTS/phalcon.zep.c:8069:13: warning: implicit declaration of function 'pcre_get_compiled_regex_cache' [-Wimplicit-function-declaration]
 8069 |  if ((pce = pcre_get_compiled_regex_cache(Z_STR_P(regex))) == NULL) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

This only affects PHP 8.2 (build OK with PHP 8.1)

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/16296

Thank you @remicollet
