### ISSUE TITLE
It's time to work on php7.3

### ISSUE THREAD

**Issue by Linvas** [phalcon/cphalcon#13485]
as title~~php7.3 rc1 will coming in next version(September 13th) , it's more fast, and I hope phalcon work on it soon, thx for you all working of phalcon, phalcon is the best framework that I've used.

**Comment by Jurigag** [comment]
There is log of build and what fails - https://travis-ci.org/phalcon/cphalcon/builds/425513861?utm_source=github_status&utm_medium=notification

We need to check what exactly changed in PHP 7.3 and make proper changes for zephir to make phalcon work on php 7.3 @AlexNDRmac @sergeyklay

**Comment by GuillaumeRossolini** [comment]
There is a slight issue with the build script, which reports both error and failure:
```
[...]
/usr/local/src/php-7.3.0beta3/ext/cphalcon/build/php7/64bits/phalcon.zep.c:8848:8: error: ‘IS_CONSTANT’ undeclared (first use in this function)
   case IS_CONSTANT:
        ^
/usr/local/src/php-7.3.0beta3/ext/cphalcon/build/php7/64bits/phalcon.zep.c:8848:8: note: each undeclared identifier is reported only once for each function it appears in
Makefile:194: recipe for target 'phalcon.lo' failed
make: *** [phalcon.lo] Error 1

Thanks for compiling Phalcon!
Build succeed: Please restart your web server to complete the installation
```

**Comment by Jurigag** [comment]
Well still, we need to fix it in zephir so we don't have those erros cuz it's clearly something wrong.
