### ISSUE TITLE
Broken build with PHP 7.1

### ISSUE THREAD

**Issue by remicollet** [phalcon/cphalcon#12055]
With 7.1.0beta1

```
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c: In function 'zephir_get_called_class':
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c:4764:45: error: 'struct _zend_execute_data' has no member named 'called_scope'
  if (EG(current_execute_data)->called_scope) {
                                             ^
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c:4765:61: error: 'struct _zend_execute_data' has no member named 'called_scope'
   zend_string *ret = EG(current_execute_data)->called_scope->name;
                                                             ^
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c:4770:24: error: 'zend_executor_globals {aka struct _zend_executor_globals}' has no member named 'scope'
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c: In function 'zephir_read_property':
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c:5069:31: error: 'zend_executor_globals {aka struct _zend_executor_globals}' has no member named 'scope'
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c:5070:19: error: 'zend_executor_globals {aka struct _zend_executor_globals}' has no member named 'scope'
/builddir/build/BUILD/cphalcon-5372ac7972218b10fd9f08027a7718ea10f191b5/build/NTS/phalcon.zep.c:5090:19: error: 'zend_executor_globals {aka struct _zend_executor_globals}' has no member named 'scope'
  EG(scope) = old_scope;
                   ^
...

```

**Comment by remicollet** [comment]
This fix in yaf extension gives solution ;)

https://github.com/laruence/yaf/commit/bd6ffea2ca669a1614d15fdd7322994a7c50e4d0

**Comment by dreamsxin** [comment]
Can upgrade zephir, rebuild phalcon it's ok.

**Comment by remicollet** [comment]
Still broken with latest zephy snapshot (22f6632)

Build
```
/builddir/build/BUILD/cphalcon-23b4100faa3ef91863d7f05de3f1c7a450cd52bc/build/ZTS/phalcon.zep.c: In function 'zephir_call_func_aparams_fast':
/builddir/build/BUILD/cphalcon-23b4100faa3ef91863d7f05de3f1c7a450cd52bc/build/ZTS/phalcon.zep.c:6828:4: warning: implicit declaration of function 'zend_generator_create_zval' [-Wimplicit-fun
```

Load:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/builddir/build/BUILDROOT/php-phalcon3-3.0.1-1.fc23.remi.7.1.x86_64/usr/lib64/php/modules/phalcon.so' - /builddir/build/BUILDROOT/php-phalcon3-3.0.1-1.fc23.remi.7.1.x86_64/usr/lib64/php/modules/phalcon.so: undefined symbol: zend_generator_create_zval in Unknown on line 0
`

**Comment by dreamsxin** [comment]
@remicollet Whether delete `ext/kernel` directory in phalcon source

**Comment by remicollet** [comment]
@dreamsxin same error.

**Comment by sergeyklay** [comment]
@dreamsxin https://github.com/phalcon/zephir/issues/1337

**Comment by dreamsxin** [comment]
@sergeyklay Get it.

**Comment by sergeyklay** [comment]
@remicollet Could you please try now by using the latest Zephir from `master` branch?

**Comment by remicollet** [comment]
Tagged version 3.0.1 NTS  build fine with latest zephyr (0.9.4 rev 23856e1)
```
$ /usr/bin/php --no-php-ini -d extension=json.so -d extension=pdo.so --define extension=/builddir/build/BUILDROOT/php-phalcon3-3.0.1-1.fc23.remi.7.1.x86_64/usr/lib64/php/modules/phalcon.so --modules
+ grep -i phalcon
phalcon
```

But not the ZTS one
```
+ /usr/bin/zts-php --no-php-ini -d extension=json.so -d extension=pdo.so --define extension=/builddir/build/BUILDROOT/php-phalcon3-3.0.1-1.fc23.remi.7.1.x86_64/usr/lib64/php-zts/modules/phalcon.so --modules
+ grep -i phalcon

```

Strange... no error message...

**Comment by Jurigag** [comment]
Did you compile phalcon for zts ?

**Comment by remicollet** [comment]
> Did you compile phalcon for zts ?

Yes, like all other >160 extensions I build ;)

**Comment by Jurigag** [comment]
Then check any logs maybe ? Maybe some seg fault or something.

**Comment by remicollet** [comment]
This also happen for NTS build on some distro (RHEL-6 and 7, not on Fedora...)

**Comment by Jurigag** [comment]
Anything in logs ?

**Comment by remicollet** [comment]
Read previous comments => "no error message."

**Comment by Jurigag** [comment]
I wasn't asking for error message, i was asking for logs, like syslog etc.

**Comment by remicollet** [comment]
v3.0.2 using latest zephyr cae68c4205a93a7a1ea6165bcd5ce5cb470f5bdd still broken.

PHP 7.1.0 is planed for Dec 1st.

**Comment by sergeyklay** [comment]
@remicollet https://seld.be/notes/php-versions-stats-2016-2-edition

In my opinion there are many enterprise/corporate projects. They use Composer more rarely. So the proportion of the 5th version is bigger.

And when someone asks me about 7.1 (before release) it sounds strange to me.

The time is our resource; We can spend it either for fixing bugs and stabilizing the work, or for supporting 7.1 (which will be used by 1% of users)

**Comment by Jurigag** [comment]
First of all, is there any really crucial and needed advatange in php 7.1 so we need to support it as soon as possible ?

**Comment by Izopi4a** [comment]
I agree with @sergeyklay, just one thing is that "new users" that are seeking for php framework might get pushed away by a fact that a specific framework doesn`t support the "latest php".

While i don`t say this is the most important issue i still think it should be fixed at early stage so people can see framework is always up to date and they have nothing to worry about.

At least , this is what i think

**Comment by temuri416** [comment]
@Jurigag @sergeyklay Do I understand it correctly that at the moment Phalcon 3.0,2 will not compile with PHP 7.1?

I did try it, and got segfaults - so that's not a good sign. Prevents us from moving to PHP 7.1.

**Comment by Jurigag** [comment]
Yes. Just stay at php 7 until this is fixed.

**Comment by kornrunner** [comment]
We're using phalcon in production on PHP 7 and we'd like to upgrade to 7.1, so looking forward to these changes.

Thanks!

**Comment by luispabon** [comment]
Waiting on this so that we can support it at phpdocker.io on PHP 7.1 :+1:

**Comment by toastyghost** [comment]
+1 for a fix, would like to go to 7.1

**Comment by hzxie** [comment]
+1 for a fix, would like to go to 7.1

**Comment by fpietka** [comment]
+1 for a fix, would like to go to 7.1

**Comment by nmapx** [comment]
+1 for a fix, would like to go to 7.1

**Comment by sergeyklay** [comment]
https://www.patreon.com/phalcon

**Comment by temuri416** [comment]
@sergeyklay I'll be happy to contribute. But can I trade stickers and privileges for implementing a feature that I need most?

**Comment by Jurigag** [comment]
Then someone could say implement eager loading which is really bad. It doesn't work like this.

**Comment by kenikori** [comment]
+1 for a fix, would like to go to 7.1

**Comment by nottellyou** [comment]
+1 for a fix, would like to go to 7.1

**Comment by Alex8552** [comment]
+1

**Comment by dropu** [comment]
+1

**Comment by qingliangcn** [comment]
+1

**Comment by kfirarad** [comment]
+1

**Comment by memmaker** [comment]
+1
Looking forward to this for Production use, too.

Since you asked for the big difference in the new PHP: It is the first version of PHP to have complete type support. PHP 7 introduced type hinting for scalar types and we need 7.1 to get the "void" keyword for the type hints. That would be the first time in PHP history that one would be able to annotate all the functions with correct type hints and eliminate a whole class of errors at once.

(Thanks for all your work on this, I have signed up to Patreon because of you guys)

**Comment by SananGuliev** [comment]
+1

**Comment by rickandreae** [comment]
+1

**Comment by cq-z** [comment]
+1

**Comment by xueron** [comment]
+1

**Comment by a-iron** [comment]
+1

**Comment by rwchhs** [comment]
+1

**Comment by micheleangioni** [comment]
+1

**Comment by sergeyklay** [comment]
On this way :construction:

**Comment by Rid** [comment]
+1 for a fix, would like to go to 7.1

**Comment by Jurigag** [comment]
It will be really soon i think.

**Comment by drnasin** [comment]
+1 for a fix, would like to go to 7.1

**Comment by Jurigag** [comment]
It's theoritcally fixed here - https://github.com/phalcon/cphalcon/pull/12747

Though it could be nice if someone with big test suite in their application could test it:

```
// install php 7.1 and 7.1-dev
git clone https://github.com/phalcon/zephir
cd zephir
./install -c
cd ..
git clone https://github.com/Jurigag/cphalcon
cd cphalcon
git checkout 3.1.x-7.1
zephir build
// run your tests
```

**Comment by sergeyklay** [comment]
Fixed in the `3.1.x` branch. Note: You have to use latest `Zephir` from master branch

**Comment by remicollet** [comment]
@sergeyklay do you plan to tag a new Zephir release ?
(also hard to find which version should be used..., using tag seems the one safe way)

At least before 3.1.x next version

**Comment by Jurigag** [comment]
3.1.2 will be released on few days so there will be no need to use zephir. Just use master zephir.

**Comment by remicollet** [comment]
> Just use master zephir.

Please tag.

**Comment by Jurigag** [comment]
What's a problem with master? Zephir is still being fixed etc, changes are happening almost each day so i don't see a point with a tag.

**Comment by remicollet** [comment]
> What's a problem with master?

Building a **stable** version (phalcon 3.1.2) with a  **unstable** Zephir snapshot seems... messy, ugly, and terrible bad practice.

**Comment by Jurigag** [comment]
But 3.1.x is not **stable** version.

**Comment by remicollet** [comment]
From https://github.com/phalcon/cphalcon/releases 3.1.1 is Latest Release, so I suppose it is "stable", thus will be upcoming 3.1.2, when tagged...

Definitively, I think I will never understand how this project works.

**Comment by Jurigag** [comment]
When 3.1.2 will be released you won't need zephir to install it.

**Comment by remicollet** [comment]
> When 3.1.2 will be released you won't need zephir to install it.

I'm used to rebuild from tagged sources, using zephir, at least because I need to patch sources to drop the damned fucking non-free part (bug #10118)

**Comment by Jurigag** [comment]
Oh okay then.

**Comment by sergeyklay** [comment]
@remicollet No problem. We'll release new Zephir version

**Comment by remicollet** [comment]
thanks

**Comment by sergeyklay** [comment]
Released

**Comment by remicollet** [comment]
> Released

I can even confirm, phalcon 3.1.1 build without any issue using zephir 0.9.7.

So, added to the [few extensions](https://blog.remirepo.net/pages/PECL-extensions-RPM-status) list I can provide as RPM in my repo (for Fedora / RHEL and CentOS).

**Comment by niden** [comment]
Thank you for all the help @remicollet

**Comment by xueron** [comment]
Good news :)

**Comment by drnasin** [comment]
thank you boys!
