### ISSUE TITLE
Cannot build falcon on Ubuntu 12

### ISSUE THREAD

**Issue by BeetLab** [phalcon/cphalcon#11955]
./install
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f 
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la   modules/* libs/*
Cleaning..
Configuring for:
PHP Api Version:         20090626
Zend Module Api No:      20090626
Zend Extension Api No:   220090626
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for icc... no
checking for suncc... no
checking whether gcc and cc understand -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20090626
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable phalcon... yes, shared
checking whether HAVE_BUNDLED_PCRE is declared... no
checking whether HAVE_JSON is declared... yes
checking for ext/json/php_json.h... yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) nawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
/bin/bash /home/nikita_a_semenov/cphalcon/build/64bits/libtool --mode=compile gcc  -I. -I/home/nikita_a_semenov/cphalcon/build/64bits -DPHP_ATOM_INC -I/home/nikita_a_semenov/cphalcon/build/64bits/include -I/home/nikita_a_semenov/cphalcon/build/64bits/main -I/home/nikita_a_semenov/cphalcon/build/64bits -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DPHALCON_RELEASE -DHAVE_CONFIG_H  -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden   -c /home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c -o phalcon.lo 
libtool: compile:  gcc -I. -I/home/nikita_a_semenov/cphalcon/build/64bits -DPHP_ATOM_INC -I/home/nikita_a_semenov/cphalcon/build/64bits/include -I/home/nikita_a_semenov/cphalcon/build/64bits/main -I/home/nikita_a_semenov/cphalcon/build/64bits -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden -c /home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_cleanup_fcache':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:4402:58: error: 'zend_class_entry' has no member named 'info'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_class_exists':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5789:53: error: 'ZEND_ACC_TRAIT' undeclared (first use in this function)
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5789:53: note: each undeclared identifier is reported only once for each function it appears in
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_read_property':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5932:3: warning: passing argument 2 of 'zend_get_object_classname' from incompatible pointer type [enabled by default]
/usr/include/php5/Zend/zend_API.h:326:14: note: expected 'char **' but argument is of type 'const char **'
usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibili
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5939:2: error: too many arguments to function 'object->value.obj.handlers->read_property'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_fetch_property_this_quick':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5976:80: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5978:26: error: 'zend_object' has no member named 'properties_table'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5978:58: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5981:18: error: 'zend_object' has no member named 'properties_table'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:5981:50: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_return_property_quick':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6039:80: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6041:26: error: 'zend_object' has no member named 'properties_table'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6041:58: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6044:18: error: 'zend_object' has no member named 'properties_table'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6044:50: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_update_property_zval':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6171:3: warning: passing argument 2 of 'zend_get_object_classname' from incompatible pointer type [enabled by default]
/usr/include/php5/Zend/zend_API.h:326:14: note: expected 'char **' but argument is of type 'const char **'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6178:2: error: too many arguments to function 'object->value.obj.handlers->write_property'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_update_property_this_quick':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6220:21: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6220:87: error: 'zend_object' has no member named 'properties_table'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6220:119: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6220:164: error: 'zend_object' has no member named 'properties_table'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6220:196: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_unset_property':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6526:3: error: too many arguments to function 'object->value.obj.handlers->unset_property'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_fetch_static_property_ce':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6609:2: warning: passing argument 2 of 'zend_read_static_property' discards 'const' qualifier from pointer target type [enabled by default]
/usr/include/php5/Zend/zend_API.h:323:16: note: expected 'char *' but argument is of type 'const char *'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_std_get_static_property':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6673:51: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:6680:50: error: 'zend_property_info' has no member named 'offset'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_create_closure_ex':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:7059:2: error: too many arguments to function 'zend_create_closure'
/usr/include/php5/Zend/zend_closures.h:33:15: note: declared here
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_http_build_query':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:10789:140: error: 'PHP_QUERY_RFC1738' undeclared (first use in this function)
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:10789:3: error: too many arguments to function 'php_url_encode_hash_ex'
/usr/include/php5/ext/standard/php_http.h:27:12: note: declared here
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_htmlspecialchars':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:10829:2: warning: passing argument 3 of 'php_escape_html_entities_ex' from incompatible pointer type [enabled by default]
/usr/include/php5/ext/standard/html.h:43:14: note: expected 'int *' but argument is of type 'size_t *'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_htmlentities':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:10854:2: warning: passing argument 3 of 'php_escape_html_entities_ex' from incompatible pointer type [enabled by default]
/usr/include/php5/ext/standard/html.h:43:14: note: expected 'int *' but argument is of type 'size_t *'
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_require_ret':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:11967:23: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_get_intval_ex':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:12891:11: error: 'IS_CALLABLE' undeclared (first use in this function)
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_get_doubleval_ex':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:12936:11: error: 'IS_CALLABLE' undeclared (first use in this function)
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_get_boolval_ex':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:12974:11: error: 'IS_CALLABLE' undeclared (first use in this function)
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_escape_html':
/home/nikita_a_semenov/cphalcon/build/64bits/phalcon.zep.c:16166:2: warning: passing argument 3 of 'php_escape_html_entities' from incompatible pointer type [enabled by default]
/usr/include/php5/ext/standard/html.h:42:14: note: expected 'int *' but argument is of type 'size_t *'
make: *** [phalcon.lo] Error 1

**Comment by Jurigag** [comment]
```
PHP Api Version: 20090626
```

Phalcon no longer support php 5.3

**Comment by BeetLab** [comment]
But we've got 5.6:

php -v
PHP 5.6.23-2+deb.sury.org~precise+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by Jurigag** [comment]
But whay `phpize -v` returns ?

**Comment by BeetLab** [comment]
well it return older api*( fuck it - installed 5.4 php and all works fine

**Comment by Jurigag** [comment]
? You can work on php 5.6 you just need to update php5-dev package using this command:

```
apt-get install php5-dev
```
