### ISSUE TITLE
502 error when setting default action in ACL

### ISSUE THREAD

**Issue by garyrutland** [phalcon/cphalcon#12557]
Sorry, accidentally posted the ticket before finishing and can't find a delete button.
Below is the code to replicate but will update the ticket as soon as I can.

```
<?php

use Phalcon\Acl;
use Phalcon\Acl\Adapter\Memory as AclList;

$this->di->set('acl', function() {
    $aclList = new AclList();

    $aclList->setDefaultAction(Acl::DENY);

    // guest
    $guest = new Acl\Role('guest');
    $aclList->addRole($guest);

    // user
    $user = new Acl\Role('user');
    $aclList->addRole($user, $guest);

    $acl = new Config\Acl();
    $acl->add($aclList);

    return $aclList;
});
```

**Comment by Jurigag** [comment]
```php
   $acl = new Config\Acl();
    $acl->add($aclList);
```

What is this?

**Comment by garyrutland** [comment]
Sorry, I was quite hastily posting this.  
That was my own code which adds the resources and allows, even with stripping that out I get a 502.

```
<?php

use Phalcon\Acl;
use Phalcon\Acl\Adapter\Memory as AclList;

$this->di->set('acl', function() {
    $aclList = new AclList();
    $aclList->setNoArgumentsDefaultAction(Acl::DENY);

    // guest
    $guest = new Acl\Role(SecurityMiddleware::ROLE_GUEST);
    $aclList->addRole($guest);

    // user
    $user = new Acl\Role(SecurityMiddleware::ROLE_USER);
    $aclList->addRole($user, $guest);

    return $aclList;
});
```
```
php-fpm_1  | [18-Jan-2017 21:20:43] WARNING: [pool www] child 20 exited on signal 11 (SIGSEGV) php-fpm_1  | [18-Jan-2017 21:20:43] WARNING: [pool www] child 20 exited on signal 11 (SIGSEGV) after 148.473834 seconds from start
php-fpm_1  | [18-Jan-2017 21:20:43] NOTICE: [pool www] child 26 started
nginx_1    | 2017/01/18 21:20:43 [error] 6#6: *4 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.24.0.1, server: localhost, request: "GET /test HTTP/1.1", upstream: "fastcgi://172.24.0.3:9000", host: "localhost"
nginx_1    | 172.24.0.1 - - [18/Jan/2017:21:20:43 +0000] "GET /test HTTP/1.1" 502 166 "-" "PostmanRuntime/3.0.9"
```

Frustratingly as well, I've been trying to downgrade my Docker image back to v3.0.0/v3.0.1/v3.0.3 via:
```
RUN git clone git://github.com/phalcon/cphalcon.git --depth=1 --branch v3.0.0 --single-branch && \
    cd cphalcon/build && \
    ./install
```
But getting an error in Docker Hub and not really sure what to make of it, only v3.0.3 seems to work.
```
[0m
Makefile:194: recipe for target 'phalcon.lo' failed

[91mmake: *** [phalcon.lo] Error 1
[0m
Removing intermediate container 70b837631a09
```

**Comment by garyrutland** [comment]
From Docker Hub:
```
gcc -I. -I/tmp/cphalcon/build/php7/64bits -DPHP_ATOM_INC -I/tmp/cphalcon/build/php7/64bits/include -I/tmp/cphalcon/build/php7/64bits/main -I/tmp/cphalcon/build/php7/64bits -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden -c /tmp/cphalcon/build/php7/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o

[91m/tmp/cphalcon/build/php7/64bits/phalcon.zep.c: In function 'zephir_get_called_class':
[0m
[91m/tmp/cphalcon/build/php7/64bits/phalcon.zep.c:4764:30: error: 'struct _zend_execute_data' has no member named 'called_scope'
  if (EG(current_execute_data)->called_scope) {
                              ^
[0m
[91m/tmp/cphalcon/build/php7/64bits/phalcon.zep.c:4765:46: error: 'struct _zend_execute_data' has no member named 'called_scope'
   zend_string *ret = EG(current_execute_data)->called_scope->name;
                                              ^
[0m
[91mIn file included from /usr/local/include/php/Zend/zend_globals.h:28:0,
                 from /usr/local/include/php/Zend/zend_compile.h:688,
                 from /usr/local/include/php/Zend/zend_modules.h:26,
                 from /usr/local/include/php/Zend/zend_API.h:27,
                 from /usr/local/include/php/main/php.h:39,
                 from /tmp/cphalcon/build/php7/64bits/phalcon.zep.c:169:
/usr/local/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'scope'
 # define EG(v) (executor_globals.v)
```
This seems to be where it stems from.

**Comment by Jurigag** [comment]
What is your php version and phalcon version?

**Comment by garyrutland** [comment]
PHP Version 7.0.9
Phalcon 3.0.3

**Comment by Jurigag** [comment]
I have simialr code and don't have this error.

**Comment by garyrutland** [comment]
Just managed to create a local docker image (no idea why it doesn't work on Docker Hub) but v3.0.2 seems to work as expected.

**Comment by garyrutland** [comment]
Interesting, it seems to be an issue when using opcache with the following settings:
```
opcache.validate_timestamps = 1
opcache.max_accelerated_files = 10000
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
```
I've just disabled it completely and seems to be working fine, I only had timestamps on because I was working locally.  
Not sure what the impact of turning off validating timestamps is yet.

**Comment by garyrutland** [comment]
Apparently I can't upload a PHP file, but I created an `acl.php` in my pubic folder with the following code:
```
<?php

use Phalcon\Acl;
use Phalcon\Acl\Adapter\Memory as AclList;
use Phalcon\Di\FactoryDefault;

error_reporting(E_ALL);

$app = new Phalcon\Mvc\Micro();
$app->setDI(new FactoryDefault());

$app->di->set('acl', function() {
    $aclList = new AclList();
    $aclList->setDefaultAction(Acl::DENY);

    // guest
    $guest = new Acl\Role('guest');
    $aclList->addRole($guest);

    // user
    $user = new Acl\Role('user');
    $aclList->addRole($user, $guest);

    return $aclList;
});

$app->handle();
```
I have opcache disabled and got a 502, after removing `$aclList->setDefaultAction(Acl::DENY);` I got an `Uncaught Phalcon\Mvc\Micro\Exception: Not-Found handler is not callable or is not defined in` which is fine because I hadn't.

**Comment by Jurigag** [comment]
https://github.com/phalcon/cphalcon/blob/master/tests/unit/Acl/Adapter/MemoryTest.php As you can see there is many tests here and no error. I will check it tomorrow in work but i doubt there will be any problem.

**Comment by garyrutland** [comment]
My docker file is public, you could try running the code via applicreation/php-fpm but you would need to link it to an nginx container etc.

**Comment by garyrutland** [comment]
I was able to figure out why my Docker builds were failing.  
I was using `php:7-fpm` which is now at `7.1.0`, once I updated the image to pull from `php:7.0-fpm` which is at `7.0.14` I was able to rollback to Phalcon v3.0.0.  
I will test my code once again tonight once I am home to see if I have any issues and see if I can upgrade to v3.0.2 instead of v3.0.3.

**Comment by Jurigag** [comment]
That's why i was asking about php version. Please next time provide FULL INFO, like follow template issue. It's created **FOR REASON**

**Comment by garyrutland** [comment]
To clarify, the PHP version I was running was `7.0.9`.  
The PHP version being used by the Docker Hub builds was `7.1.0` but because it never succeeded I never used it locally.

**Comment by Jurigag** [comment]
On 7.0.13 this code works for me without any problem:

```php
$di = new \Phalcon\Di\FactoryDefault();
$di->set('acl', function() {
    $aclList = new AclList();

    $aclList->setDefaultAction(Acl::DENY);

    // guest
    $guest = new Acl\Role('guest');
    $aclList->addRole($guest);

    // user
    $user = new Acl\Role('user');
    $aclList->addRole($user, $guest);
    return $aclList;
});
$acl = $di->get('acl');
var_dump($acl->isRole('guest'));
```

**Comment by garyrutland** [comment]
Ok cool, will try with 7.0.14 tonight.
