### ISSUE TITLE
Can't build phalcon v3.0.x using zephir

### ISSUE THREAD

**Issue by gabel** [phalcon/cphalcon#12525]
Cannot compile phalcon with zephir via travis-ci on latest 3.0.x version.  This is related to #12509 and the reverted fix of https://github.com/phalcon/cphalcon/commit/3e7168561420dc39361019f4942007daf4850f15 

I guess the fix should not be reverted in 3.0.x or changes from master need to be backported. We cannot build phalcon anymore in our build environment. 👎 

```
Zephir\CompilerException: Class '\Imagick' does not implement static method: 'getVersion' in /home/travis/cphalcon/phalcon/image/adapter/imagick.zep on line 363
	   let version = \Imagick::getVersion();
	---------------------------------------^
```

See https://travis-ci.org/gabel/phalcon-ci-installer/builds/188467993

### Details

* Phalcon version: 3.0.3
* PHP Version: PHP 7.0.14 (cli) (built: Dec 21 2016 13:11:55) ( ZTS )
* Operating System: Ubuntu 12.04.5 LTS 
* Installation type: Compiling from source 
* Zephir version (if any): 0.9.4
* Server: -

**Comment by sergeyklay** [comment]
@gabel You have to use latest Zephir from the `master` branch

**Comment by gabel** [comment]
@sergeyklay Will there be a working tag on ^0.9 for this?

**Comment by sergeyklay** [comment]
Will work fine with `1.0.x-dev` or `dev-master`. I'll release new Zephir version for Phalcon 3.0.4 to avoid the inconvenience described above

**Comment by gabel** [comment]
@sergeyklay 

We're using https://github.com/techpivot/phalcon-ci-installer and it requires `^0.9` so I need to replace our dependency with a patched version using zephir dev-master.

Thanks for the fast feedback!!! 👍

**Comment by virgofx** [comment]
Updated to use `dev-master` for now, can someone cut a new tag for Zephir.

**Comment by sergeyklay** [comment]
@virgofx Done
