### ISSUE TITLE
[BUG]:  [5.0.0alpha4] build failure with PHP 8.0 #2267 

### ISSUE THREAD

**Issue by remicollet** [phalcon/cphalcon#15645]
Build OK with 7.4, KO with 8.0, from the v5.0.0alpha4 tag

```
/builddir/build/BUILD/php80-php-phalcon5-5.0.0~alpha4/NTS/phalcon.zep.c:34672:33: error: 'PsrLinkLinkInterface_ce_ptr' undeclared (first use in this function)
34672 |   Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)

```

Could be related to afe86a47bafe2bb8885349e526e94b95ae384805

**Comment by Jeckerson** [comment]
The headers were removed because PSR detection passed to be dynamic during runtime. But what I also noticed during this morning is that Zephir did not generate correct code for PSR class entries inside Phalcon project...

Wrong:
```c
Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)
```

Correct:
```c
Z_PARAM_OBJECT_OF_CLASS(link, zephir_get_internal_ce(SL("psr\\link\\linkinterface")))
```

There will be new release with updated version of Zephir and updated code in phalcon.c.

**Comment by Jeckerson** [comment]
Closing in favour #15647

**Comment by Jeckerson** [comment]
Now there is an separate CI to install from `build/` directory and to make sure that this kind of bugs won't repeat.

https://github.com/phalcon/cphalcon/actions/runs/1210609721
