### ISSUE TITLE
[BUG] Volt Function Argument Error

### ISSUE THREAD

**Issue by LearnPhalcon** [phalcon/cphalcon#13943]
This code worked fine in ``4.0.0-alpha.2`` but not in ``alpha3 and alpha4`` what changed and how to fix it? I'm using PHP v7.3.4

```
ArgumentCountError:
Too few arguments to function Closure::{closure}(), 1 passed and exactly 2 expected
/project/app/config/bootstrap.php (62)

#0  Closure->{closure}(Object(Phalcon\Mvc\View))
#1  call_user_func(Object(Closure), Object(Phalcon\Mvc\View))
#2  Phalcon\Mvc\View->loadTemplateEngines()
#3  Phalcon\Mvc\View->render(index, test)
#4  Phalcon\Mvc\Application->handle(/)
```

```php
$di->set('view', function() {
  $view = new View();
  $view->setViewsDir('../app/views/');
  $view->registerEngines([
    '.volt' => function($view, $di) {  // Line: #62
      $volt = new Volt($view, $di);
      $volt->setOptions([
        'compiledPath' => '../app/cache/',
        'compiledExtension' => '.html',
        'compiledSeparator' => '_',
      ]); #options
      return $volt;
    } #volt
  ]); #engines
  return $view;
}); #view
```

Thank You!

**Comment by v00v** [comment]
It actually worked in **4.0.0-alpha1** using PHP v7.3.2. I haven't tested in in alpha2 but in alpha3 and alpha4 has this error.

**Comment by sergeyklay** [comment]
Please take a look at the change log https://github.com/phalcon/cphalcon/blob/master/CHANGELOG-4.0.md#400-alpha3-2019-02-31

![image](https://user-images.githubusercontent.com/1256298/55544854-a4d52b80-56d4-11e9-923a-a3a16bebe2df.png)

**Comment by v00v** [comment]
@sergeyklay Thank you, I missed this in changelog. I wish you guys had important changes like this in seperate section in changelog. Like "Important" to indicate that it breaks previous features. I can confirm now, that this is not a bug. Below code works in ``v4.0.0-alpha.3`` I haven't tried ``v4.0.0-alpha.4-pre-release`` will wait for ``v4.0.0-alpha.4-stable`` to test that.

```php
$di->set('view', function() {
  $view = new View();
  $view->setViewsDir('../app/views/');
  $view->registerEngines([
    '.volt' => function($view) {
      $volt = new Volt($view, $this);
      $volt->setOptions([
        'compiledPath' => '../app/cache/',
        'compiledExtension' => '.html',
        'compiledSeparator' => '_',
      ]); #options
      return $volt;
    } #volt
  ]); #engines
  return $view;
}); #view
```
